name: Update project estimates

on:
  project:
    types: [created]
  project_card:
    types: [moved, created, edited, deleted]
  project_column:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update project column estimates
    steps:
      - name: Use API to calculate and update total estimates in each column
        id: run
        uses: emiliopedrollo/github-estimates-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
